version: 2

steps: &steps
  steps:
    - checkout
    # Download and cache dependencies
    - restore_cache:
        keys:
        - dependencies-{{ checksum "Gemfile.lock" }}
        # fallback to using the latest cache if no exact match is found
        - dependencies-
    - run:
        name: install dependencies
        command: bundle install --jobs=4 --retry=3 --path vendor/bundle
    - save_cache:
        paths:
          - ./vendor/bundle
        key: dependencies-{{ checksum "Gemfile.lock" }}

    - run: bundle exec rake run_task_from_env

jobs:
  ruby-2.4:
    docker:
      - image: circleci/ruby:2.4
    environment:
      - TASK: spec
    <<: *steps

  ruby-2.5:
    docker:
      - image: circleci/ruby:2.5
    environment:
      - TASK: spec
    <<: *steps

  ruby-2.6:
    docker:
      - image: circleci/ruby:2.6
    environment:
      - TASK: spec
      - CODECOV: true
    <<: *steps

  jruby-latest:
    docker:
      - image: circleci/jruby:latest
    environment:
      - TASK: spec
    <<: *steps

  rubocop:
    docker:
      - image: circleci/ruby:2.6
    environment:
      - TASK: rubocop
    <<: *steps


workflows:
  version: 2
  build:
    jobs:
      - ruby-2.4
      - ruby-2.5
      - ruby-2.6
      - jruby-latest
      - rubocop
